trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - script: |
      docker pull emavi/batch-simulation-engine:v1.0.0
    displayName: "Pull simulation image from DockerHub"

  - script: |
      docker run \
        --cpus="1.0" \
        --memory="512m" \
        emavi/batch-simulation-engine:v1.0.0
    displayName: "Run batch simulation container"

