trigger:
  branches:
    include:
      - main

variables:
  dockerHubRepo: aavanish/batch-simulation-engine
  acrRepo: batch-simulation-engine
  imageTag: $(Build.BuildId)

pool:
  vmImage: ubuntu-latest

stages:
- stage: BuildAndPublish
  displayName: "Build and Publish Container Image"
  jobs:
  - job: ContainerBuild
    displayName: "Container Build Job"
    steps:

    - checkout: self

    - task: Docker@2
      displayName: "Build and Push to Docker Hub"
      inputs:
        containerRegistry: dockerhub-connection
        repository: $(dockerHubRepo)
        command: buildAndPush
        Dockerfile: container/simulation-runtime.Dockerfile
        tags: |
          $(imageTag)
          latest

    - task: Docker@2
      displayName: "Build and Push to Azure Container Registry"
      inputs:
        containerRegistry: acr-connection
        repository: $(acrRepo)
        command: buildAndPush
        Dockerfile: container/simulation-runtime.Dockerfile
        tags: |
          $(imageTag)
