trigger: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: batch-simulation-engine
  imageTag: v1.0.1
  acrLoginServer: aavanishacr.azurecr.io

steps:
  - script: |
      docker pull emavi/batch-simulation-engine:v1.0.0
    displayName: "Pull image from DockerHub"

  - script: |
      docker tag \
        emavi/batch-simulation-engine:v1.0.0 \
        $(acrLoginServer)/$(imageName):$(imageTag)
    displayName: "Tag image for ACR"

  - task: Docker@2
    displayName: "Push image to ACR"
    inputs:
      command: push
      repository: $(imageName)
      tags: |
        $(imageTag)
      containerRegistry: acr-aavanish-connection

